export const categoryArt: Record<string, string> = {
  politics: '/img/category/politics.svg',
  science: '/img/category/science.svg',
  books: '/img/category/books.svg',
  cinema: '/img/category/cinema.svg',
  philosophy: '/img/category/philosophy.svg',
  'my-questions': '/img/category/my-questions.svg',
  'entangled-minds': '/img/category/entangled-minds.svg',
  'unpolished-beginner': '/img/category/unpolished-beginner.svg',

  'action-adventure': '/img/category/action-adventure.svg',
  comedy: '/img/category/comedy.svg',
  drama: '/img/category/drama.svg',
  'science-fiction': '/img/category/science-fiction.svg',
  horror: '/img/category/horror.svg',
  romance: '/img/category/romance.svg',
  thriller: '/img/category/thriller.svg',
  fantasy: '/img/category/fantasy.svg',
  musical: '/img/category/musical.svg',
  'historical-non-fiction': '/img/category/historical-non-fiction.svg',
  animation: '/img/category/animation.svg',
  western: '/img/category/western.svg',
  'psychological-tragedy': '/img/category/psychological-tragedy.svg',
  'cinema-as-whole': '/img/category/cinema-as-whole.svg',
  'short-films': '/img/category/short-films.svg',
}
